### ISSUE TITLE
Marvelousga bug

### ISSUE THREAD

**Issue by bullik01** [Citrinate/giveawayHelper#1]
Failed! Please make sure you completed all tasks and your steam profile is public. 
![screenshot-marvelousga com-2017-06-13-17-56-16](https://user-images.githubusercontent.com/4389593/27088918-aea5b51a-5061-11e7-9463-da18856d0490.png)

=========
= VERSIONS =
=========

giveawayHelper: 2.0.1
Firefox: Latest
Greasemonkey: 3.11

=========

My Steam profile is open & public.

**Comment by Citrinate** [comment]
In the screenshot it says "Join Marvelousga", meaning you're not already a member of that group.

I actually did the same thing myself earlier today.  The color I've chosen blends in with the color scheme and doesn't draw the needed attention.  In the next update I plan to swap the Join/Leave colors.

**Comment by bullik01** [comment]
I am leave from this group after press "Get My Key" (and after capcha)

**Comment by Citrinate** [comment]
When you click on "Join Marvelousga", the effect is not immediate.  It will take a few seconds before you've actually joined the group.  Perhaps you clicked "Get My Key" before it finished.

Is this a common occurrence?  I just tested on Firefox and had no issues.

**Comment by mikuhl-dev** [comment]
On Marvelousga they used to only require joining steam groups, but now some giveaways have PointsPrizes tasks which are also mandatory. (They have your email or something)
