### ISSUE TITLE
New GA site | woobox.com (similar to gleam.io)

### ISSUE THREAD

**Issue by bullik01** [Citrinate/giveawayHelper#10]
New GA site | woobox.com (similar to gleam.io)

**Comment by Citrinate** [comment]
Not really sure what this script could add to Woobox.  I do sometimes see Woobox giveaways where they ask for Facebook Likes or Tweets, but it's always optional.

**Comment by bullik01** [comment]
What about twitter, youtube, twitch on Woobox?

**Comment by Citrinate** [comment]
I went searching through some of the active Woobox giveaways, and I couldn't find any with those sorts of requirements.
