### ISSUE TITLE
Why does not support one-click confirmation group?

### ISSUE THREAD

**Issue by wang93wei** [Citrinate/giveawayHelper#15]
As you can see, marvelousga this site is verified by spelling &verify + ID in the form after the page.
![qq 20170702004720](https://user-images.githubusercontent.com/6371053/27763958-afd4c9cc-5ec0-11e7-9547-930e913fbd81.png)
![qq 20170702005938](https://user-images.githubusercontent.com/6371053/27764004-cd42046a-5ec1-11e7-9e3f-e70173857376.png)

Each task has a unique ID.
![qq 20170702010124](https://user-images.githubusercontent.com/6371053/27764025-2158f982-5ec2-11e7-8c67-d50f83f5a410.png)

So, can you do this function?

**Comment by bullik01** [comment]
I try this, it not work.
It's not real confirmation.

**Comment by Citrinate** [comment]
My goal for this script is to add new features to these sites, but not to change any features they currently have.  So sorry, but I don't plan to add anything like this.

Also, there's no need to click "Verify" for the tasks at MarvelousGA.  Simply join the Steam Groups, complete the Captcha, and click "Get My Key".  There used to be a single task that did require verification ([detailed here](https://github.com/Citrinate/giveawayHelper/issues/1#issuecomment-309490175)), but I haven't seen it in a while.

**Comment by gekkedev** [comment]
Would add this to my extension, but there seem to be different task types. I can bypass the gamehag tasks, but full automation would make it break too fast.
