### ISSUE TITLE
Help w/ adding new GA sites

### ISSUE THREAD

**Issue by bullik01** [Citrinate/giveawayHelper#18]
Can u help me adding new GA site? 
For simple i try add support for ghame.ru. But it's not worked :(

What i do:

1. Added "match" on top of script:
`// @match *://*.ghame.ru/*`
2. Added strings to setup config:
`						{
							hostname: ["ghame.ru", "www.ghame.ru"],
							helper: basicHelper,
							cache: true
							offset: [80, 0, 0]
						},`

Full script: https://puu.sh/wJaEZ/535dd30fc4.js

Please tell me what i do wrong...? Thanks

**Comment by Citrinate** [comment]
This site doesn't work like any of the others, there's no direct link to giveaway pages, everything is loaded in dynamically.  The links to the Steam groups aren't there when the page first loads, and so the script can't find them.  Changes will need to be made to the script before it can run on this site.

**Comment by bullik01** [comment]
Ok. What i need change?

**Comment by Citrinate** [comment]
I see nothing wrong with the config entry you wrote.  basicHelper needs to be updated so that it continually monitors for changes rather than running only one time when the page loads.
