### ISSUE TITLE
Key Champions group bugs

### ISSUE THREAD

**Issue by bullik01** [Citrinate/giveawayHelper#20]
U can see all on screenshot >>> https://puu.sh/wMWAq/32951a8986.jpg

**Comment by Citrinate** [comment]
I'm not seeing the same thing when I visit that page.  I only have 6 group buttons.

**Comment by bullik01** [comment]
buttons is duplicating by join & verify one step...

**Comment by Citrinate** [comment]
Not sure what you mean by that.  I'm able to complete a giveaway without seeing duplicate buttons.

**Comment by Citrinate** [comment]
Tested on Firefox and was able to reproduce.  Hopefully will have a fix out soon.

**Comment by Citrinate** [comment]
This bug should be fixed now in v2.0.10

**Comment by bullik01** [comment]
Fixed
