### ISSUE TITLE
Watch a YouTube video til the end

### ISSUE THREAD

**Issue by pannal** [Citrinate/giveawayHelper#25]
Am I missing something, or will this just work for gleam?

`yt.player.exports.navigate("100%")`

**Comment by Citrinate** [comment]
Yeah, there's ways to get around those sorts of forced video watches.

However, I don't plan on adding anything like this to the script.  Manipulating tasks like this comes with it the possibility of being banned.

**Comment by pannal** [comment]
Fair enough :)
