### ISSUE TITLE
Twitch authentication

### ISSUE THREAD

**Issue by psyren89** [Citrinate/giveawayHelper#26]
The helper constantly gives me warnings saying I need to be logged into Twitch (I am).

The developer console says that requests to `/api/viewer/token.json` get this response:
```
{error: "Not logged in", status: 401, url: "/api/viewer/token.json"}
```

Even with all my blocking plugins disabled (as well as HTTPS Everywhere), the problem persists.

**Comment by Citrinate** [comment]
I'm not able to reproduce this bug in either Firefox or Chrome.

**Comment by bullik01** [comment]
I don't see this bug on my Firefox

**Comment by psyren89** [comment]
I just tried it in Firefox, and there doesn't seem to be an issue. I'll dig a bit deeper in Chrome.

**Comment by psyren89** [comment]
Found the issue: Privacy Badger was blocking cookies from `player.twitch.tv`.
