### ISSUE TITLE
[request] feature to redeem the key 

### ISSUE THREAD

**Issue by mahadi22** [Citrinate/giveawayHelper#28]
just want to give idea, how about adding feature to redeem the key after it got revealed...??
maybe a button to redirected to steam web activation https://store.steampowered.com/account/registerkey?key=xxxxx-xxxxx-xxxxx

or redeem it after pressing a button using script provided by steam https://steamstore-a.akamaihd.net/public/javascript/registerkey.js?v=w0CB9Fw6WLoQ&l=english ( https://pastebin.com/VHgEYWLa in case its not available),
its using ajax post and the parameter are product key and g_sessionID

thank you~~~♥

**Comment by Citrinate** [comment]
Good idea.  I've added this to the latest version.
