### ISSUE TITLE
Delete Tweet not showing when share popup shows - Gleam

### ISSUE THREAD

**Issue by nihaals** [Citrinate/giveawayHelper#30]
When you have just 2 entry options left on Gleam, Share and Tweet (This may be a bug for any kind of entry that should show a button), and you click tweet, the popup for sharing shows, and so the `Delete Tweet` button doesn't show

**Comment by Citrinate** [comment]
Could you link me to a giveaway that has this issue (even if it's ended by now).  Please also make sure you're using at least version 2.4.2, as a recent issue #29 also caused Twitter buttons to not appear and has been fixed.

**Comment by nihaals** [comment]
https://gleam.io/EfTZi/gamerlink-hyperx-cloud-alpha-giveaway and using 2.4.3
I got the issue when I had done all of the entries, came back the next day, did the daily tweet and the share popup came, causing it to happen

**Comment by Citrinate** [comment]
Should be fixed now in v2.5.1
