### ISSUE TITLE
TypeError: LEVEL_PATTERN.exec(...) is null

### ISSUE THREAD

**Issue by blue-lightning** [Citrinate/giveawayHelper#32]
The latest update from Indiegala broke the script.

Error at line igautoenter.user.js:268:28

giveaways.push(new Giveaway({
        id: $(".ticket-right .relative", giveawayDOM).attr("rel"),
        name: $(".game-img-cont a", giveawayDOM).attr("title"),
        price: parseInt($(".ticket-price strong", giveawayDOM).text()),
        **minLevel: parseInt(LEVEL_PATTERN.exec(infoText)[1]),**
        owned: undefined, //will be filled in later in setOwned()
        participants: parseInt(PARTICIPANTS_PATTERN.exec($(".ticket-info-cont .fa.fa-users", giveawayDOM).parent().text())[1]),
        guaranteed: infoText.indexOf("not guaranteed") === -1,
        by: $(".ticket-info-cont .steamnick a", giveawayDOM).text(),
        entered: $(".ticket-right aside", giveawayDOM).length === 0,
        steamId: steamId,
        idType: idType,
        gameId: gameId
      }));

**Comment by Citrinate** [comment]
I believe you meant to post this over here: https://github.com/Hafas/indiegala-auto-enter
