### ISSUE TITLE
doesnt seem to work gleam.io

### ISSUE THREAD

**Issue by sirus20x6** [Citrinate/giveawayHelper#33]
doesnt seem to do anything. script says it's running. chrome on linux

**Comment by Citrinate** [comment]
What is it not doing that you're expecting it to do?

On most sites the script will add [a bar](https://raw.githubusercontent.com/Citrinate/giveawayHelper/master/images/marvelous.png) to the top of the page.  This bar does not appear for Gleam.io, instead the action buttons are added next to each entry [as so](https://raw.githubusercontent.com/Citrinate/giveawayHelper/master/images/gleam.png).

**Comment by sirus20x6** [comment]
https://i.imgur.com/8Of0z3l.png i dont see anything different

**Comment by Citrinate** [comment]
There's nothing wrong with the image you've posted.

The Twitter action buttons will only appear after you've completed those entries.

The Steam entry in that image isn't a traditional Steam entry, and so there's nothing for the script to do.  You technically don't need to join the group they mention to get credit for joining.  Entering anything into the text box and hitting "continue" will validate the entry.

However if you lie about joining the Steam group you will be disqualified.  The same is also possibly true for deleting Tweets and unfollowing Twitter users.

You can find an example of what Steam group entries typically look like [here](https://gleam.io/W4GAG/every-entry-type).
