### ISSUE TITLE
A special KEY

### ISSUE THREAD

**Issue by shaww855** [Citrinate/giveawayHelper#35]
https://whosgamingnow.net/giveaway/sr  
`56788-97019-76086-29863-12527`  
Giveaway Helper generated a wrong link:  
https://store.steampowered.com/account/registerkey?key=56788-97019-76086

**Comment by gekkedev** [comment]
https://github.com/Citrinate/giveawayHelper/blob/master/giveawayHelper.user.js#L564
The "lookbehind" feature would be useful for this. Else it gets really messy.
