### ISSUE TITLE
Tampermonkey 4 - Firefox not working

### ISSUE THREAD

**Issue by nihaals** [Citrinate/giveawayHelper#37]
I've tried the script with Tampermonkey on Firefox with no other plugins enabled, and it doesn't work, but with Greasemonkey, it does

**Comment by Citrinate** [comment]
Thanks for reporting this.  It should be fixed now in v2.7.5

**Comment by nihaals** [comment]
Thanks! I noticed this back when I switched to Firefox around a month ago, but I thought it was something on my end, but I'm glad it was sorted for anyone also having the issue 😄
