### ISSUE TITLE
bananagiveaway.com not working

### ISSUE THREAD

**Issue by nihaals** [Citrinate/giveawayHelper#39]
On https://www.bananagiveaway.com, it adds the top bar but doesn't add any buttons: ![image](https://user-images.githubusercontent.com/18350092/36550058-32551ac0-17ec-11e8-85c4-75f6b8159af4.png)
Example: https://www.bananagiveaway.com/giveaway/19

**Comment by Citrinate** [comment]
Should be fixed now
