### ISSUE TITLE
OrlyGift Auto Voter

### ISSUE THREAD

**Issue by bullik01** [Citrinate/giveawayHelper#4]
Hi. I can add OrlyGift Auto Voter on giveawayHelper. Votes give orlygift points for free. For orlygift points u can buy some games on orlygift store.

Do u want it?

**Comment by Citrinate** [comment]
Thanks, but no thanks.  I don't think it's a good fit for this project.  The intention is for this to be a "safe" script, something people shouldn't be getting banned for using.

**Comment by bullik01** [comment]
Ok. No problem. Closed.
