### ISSUE TITLE
Steam curator

### ISSUE THREAD

**Issue by RansoTR** [Citrinate/giveawayHelper#44]
not work follow steam curator

**Comment by Citrinate** [comment]
It's my understanding that the Steam API does not provide a way to let developers know that a user is following a Steam Curator.

Giveaway sites may ask you to follow someone, but they can't actually check to see that you've done it.  When you're asked to follow someone, clicking the link should be enough to validate that step.

**Comment by Citrinate** [comment]
Re-opening this because I'd like to add this feature for Giveaway.su
