### ISSUE TITLE
Problem with "giveaway.su"

### ISSUE THREAD

**Issue by LazenSlay** [Citrinate/giveawayHelper#49]
Hi, it worked fine for a couple of weeks but now it just say "Giveaway Helper Error: You must be logged into steamcommunity.com" (which i am already), so, don't know if it just me or is a problem with the script.
Here's a screen of it
https://k62.kn3.net/2/5/E/3/4/F/3C4.jpg

**Comment by Citrinate** [comment]
If there's something wrong with the script, then you should see this error on all of the other giveaway sites the script supports.  If you only see it occasionally, then it's probably an issue on Steam's end that will resolve itself after some time.

**Comment by LazenSlay** [comment]
Just tried "Banana Giveaway" and "Prys.ga" and on both of them got the same error message. Also tried disabling all other chrome extensions but didn't work either.

**Comment by Citrinate** [comment]
Could you try installing v2.9.0 from [here](https://github.com/Citrinate/giveawayHelper/raw/c9c627d97ef4e1e7d6db22da16338ba4551ef0c8/giveawayHelper.user.js) and seeing if that version works?

**Comment by LazenSlay** [comment]
same result, i installed the script at the end of may, don't remember wich version was back then

**Comment by Citrinate** [comment]
Thanks for reporting this, it should be fixed now in v2.10.1

**Comment by LazenSlay** [comment]
It seems that now is linking ok with my steam account, but it just doesn't do anything
https://k62.kn3.net/F/F/6/0/F/5/778.png
If i do it manually (without entering in any steam group/curator) i can complete this tasks
https://k62.kn3.net/8/D/A/3/E/4/947.jpg

**Comment by Citrinate** [comment]
Clicking the buttons the script generates will only cause you to Join or Leave a Steam Group.  If there's a button on the site that you also need to click to verify this, the script won't automatically do that for you.

There's nothing wrong with Giveaway.su showing that green checkmark without you having joined the groups.  The verification actually happens at a later stage, and if you aren't in the necessary groups by then, that's where you'll see an error message.

**Comment by LazenSlay** [comment]
You're right, i realize i was using 2 different scripts, one was this and other one called "Giveaway.su - Auto Solver" but it doesn't seem to work anymore. 
Thanks mate, cheers from Argentina!

**Comment by Citrinate** [comment]
I think that this script [here](https://github.com/gekkedev/GiveawayKiller) will let you skip most of the Giveaway.su tasks
