### ISSUE TITLE
Follow/Unfollow curators

### ISSUE THREAD

**Issue by psydex** [Citrinate/giveawayHelper#56]
Can you add a button to follow/unfollow curators the same way as join/leave groups?
It would come in handy for giveaways where such task exist (e.g. Giveaway su)

**Comment by Citrinate** [comment]
I recommend using this script to bypass those requirements.  With it, all you need to do is click on the verify button to get credit for those tasks.

https://github.com/gekkedev/GiveawayKiller/raw/5d3a5dfb2f929e1a08a9023ce8eb716f619c9052/giveawayKiller.user.js

**Comment by psydex** [comment]
I'll give it a shot, thank you


EDIT: It works!

**Comment by psydex** [comment]
Giveaway Killer does NOT unfollow currators

**Comment by Citrinate** [comment]
The script I linked to only works on Giveaway.su.  As far as I'm aware, no other giveaway sites actually check whether or not you've followed a curator.  Using the script, you shouldn't need to follow any curators for it to have to unfollow them.

**Comment by Citrinate** [comment]
I've added Follow/Unfollow Steam Curator buttons for Giveaway.su.

Some people have reported being banned for using the GiveawayKiller fork I linked to above, and so I no longer recommend its use.
