### ISSUE TITLE
Script doing nothing :(

### ISSUE THREAD

**Issue by sebflex** [Citrinate/giveawayHelper#59]
Script is doing nothing on a gleam.io site :(

**Comment by Citrinate** [comment]
I'm not noticing any issues on Gleam giveaways.  It would be helpful if you could link the giveaway you're having issues with.

I've released v2.12.5 which fixes a bug that may or may not be related to this issue.  You could also check to see if this new version fixes the problem.

**Comment by sebflex** [comment]
> I'm not noticing any issues on Gleam giveaways. It would be helpful if you could link the giveaway you're having issues with.
> 
> I've released v2.12.5 which fixes a bug that may or may not be related to this issue. You could also check to see if this new version fixes the problem.

Could you write a short 'How to'? Because for me the script isn't working. I installed it in Chrome and Firefox, opened a gleam.io site, but the script was doing nothing...I double checked that i was running, and it was :(

**Comment by Citrinate** [comment]
What are you expecting it to do that it's not doing?  There's a [screenshot](https://raw.githubusercontent.com/Citrinate/giveawayHelper/master/images/gleam.png) previewing what it should look like when the script is running.  You can test it on this giveaway:

https://gleam.io/W4GAG/every-entry-type

While the screenshot shows Twitter buttons, those are no longer working as explained in #42.

**Comment by sebflex** [comment]
> What are you expecting it to do that it's not doing? There's a [screenshot](https://raw.githubusercontent.com/Citrinate/giveawayHelper/master/images/gleam.png) previewing what it should look like when the script is running. You can test it on this giveaway:
> 
> https://gleam.io/W4GAG/every-entry-type
> 
> While the screenshot shows Twitter buttons, those are no longer working as explained in #42.

Well for me it doing nothing after I entered a gleam.io contest site, it's running like I said, but it's doing no action at all. Not a single entry type done

**Comment by Citrinate** [comment]
> Not a single entry type done

What do you mean by this?  The script will not complete any of the tasks automatically.

Also be aware that if you're not logged into a Gleam.io account when you visit a giveaway (and also possibly if you're not logged into any of the required accounts: Steam or Twitch), then the script will do nothing.

**Comment by sebflex** [comment]
Not automatically??...well that's pretty bad
