### ISSUE TITLE
Script not working - Opera 58.0.3135.127 (Tampermonkey 4.8.5890)

### ISSUE THREAD

**Issue by Kondoru** [Citrinate/giveawayHelper#60]
Hi,

I have all accounts linked and verified but the script is not generating the buttons on the giveaways pages, the script was extracted from the raw page and don't show any errors in the tampermonkey and in a verifier page, it's the only script installed and all the permissions to the tampermonkey are granted and it's the only extension installed too.

Here's what the [Tampermonkey](https://i.imgur.com/1GRlGez.png) show and what is showed in the [giveaway boxes](https://i.imgur.com/bAlaqCz.png).

And since I don't know JS, I'm pretty much lost here, thanks in advance!

**Comment by Citrinate** [comment]
On this [giveaway](https://gleam.io/W4GAG/every-entry-type-example-competition), do you see a "Join Group" button next to the "Join group Dotabuff on Steam" requirement?

Currently the script only supports the first (and maybe last) Twitch requirement shown in your screenshot.  It could be that only the Twitch requirement support is broken.

**Comment by Kondoru** [comment]
Thanks for answering!

Just tried here and immediatelly the helper warned about the steamcommunity error, apparently the Steam didn't "validated" the community, after that the only button that appeared was the Steam one, the twitter ones didn't appeared but thanks!

**Comment by Citrinate** [comment]
v2.12.6 should fix the issue with Twitch buttons not showing up on Gleam.io
